### PR TITLE
Fixed Password: passwordform="plain"

### PR DESCRIPTION
**Pull request by AKA-47**
New Api uses password like this:
```
<Username>admin</Username : Username should be of valid administrator profile user
<Password passwordform="plain">  : When this method is used password needs to provide in plain text
<Password passwordform="encrypt"> : when this method is used password should be in encrypted text derive from user property.
```

I fixed this to make it usable in v18

### CODE REVIEW

**Comment by richardstrnad** [comment]
Hi, Thanks for the PR!
Is this part correct?
```
</Username>passwordform='plain'>
```
Or is the `<Password ` missing?

**Review by AKA-47 — COMMENTED** [review]
fixed missing <Password

**Comment by AKA-47** [comment]
yes, that was actually missing. I don't know where it went. good if someone is careful

**Comment by richardstrnad** [comment]
Thanks for the work!

**Pull request merged**
